<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="MyfirstRepo"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="1.096">
    <properties></properties>

            <testcase
                name="verifyDeleteBook"
                time="1.096"
                classname="com.vapasi.RestAssured.RestAPITests.GetBopokAPIResponseTest">

            <failure type="java.lang.AssertionError" message="expected [book is successfully deleted] but found [Delete Book operation failed, looks like the book doesnt exists]">
                <![CDATA[java.lang.AssertionError: expected [book is successfully deleted] but found [Delete Book operation failed, looks like the book doesnt exists]
                org.testng.Assert.fail(Assert.java:99)org.testng.Assert.failNotEquals(Assert.java:1037)org.testng.Assert.assertEqualsImpl(Assert.java:140)org.testng.Assert.assertEquals(Assert.java:122)org.testng.Assert.assertEquals(Assert.java:629)org.testng.Assert.assertEquals(Assert.java:639)com.vapasi.RestAssured.RestAPITests.GetBopokAPIResponseTest.verifyDeleteBook(GetBopokAPIResponseTest.java:79)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:564)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1511)org.testng.TestRunner.privateRun(TestRunner.java:794)org.testng.TestRunner.run(TestRunner.java:596)org.testng.SuiteRunner.runTest(SuiteRunner.java:377)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)org.testng.SuiteRunner.run(SuiteRunner.java:276)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)org.testng.TestNG.runSuitesLocally(TestNG.java:1134)org.testng.TestNG.runSuites(TestNG.java:1063)org.testng.TestNG.run(TestNG.java:1031)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>


</testsuite>
